### ISSUE TITLE
Bug: No results without authentification

### ISSUE THREAD

**Issue by adrpar** [aipescience/uws-client#1]
toelva:bin adrian$ ./uws -H ... results ...
Downloading result into file 'result.dat'
Traceback (most recent call last):
  File "./uws", line 324, in <module>
    resultsJob(args.host, args.user, args.pwd, args.id)
  File "./uws", line 156, in resultsJob
    UWSconn.downloadFile(url, usr, pwd, filename, callback=printProgress)
  File "/Users/adrian/Documents/eScience/Tools/uws-client/./lib/UWS/connection.py", line 129, in downloadFile
    request.add_header("Authorization", "Basic %s" % self.authStr)
AttributeError: connection instance has no attribute 'authStr'

**Comment by kristinriebe** [comment]
The current version returns "No permission to access this resource", if someone tries to download results from a job without given the credentials. That sounds OK to me, so we can close this issue, right?
